### ISSUE TITLE
Add var for plans also

### ISSUE THREAD

**Issue by ramanveerji** [SpringsFern/TG-FileStreamBot#3]
Let owner use any amount of links and give him authority to distribute paid/ plus plans to any users.

**Comment by anikethjana1** [comment]
If you want to make money out of a free and open source project , you better create your own instead of begging for irrelevant features

**Comment by ramanveerji** [comment]
> If you want to make money out of a free and open source project , you better create your own instead of begging for irrelevant features 

You should take care of your logs, don't poke your nose here.
